### ISSUE TITLE
Lecturer course page

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/gits-frontend#51]
## Description
The Course page should be also have an appropriate view for lectureres. 
First we need a concept to know, how it should look like concretly. That makes it easier to know how to code it.
The other thing is obviously the implmentation of the concept.

## Acceptance Criteria

- [x] Concept is done
- [x] Implementation is working correctly

## Children

- [x] #50 
- [x] https://github.com/IT-REX-Platform/wiki/issues/59
