### ISSUE TITLE
Frontend lecturer course creation page

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/gits-frontend#9]
## Description
The page the lecturer sees when the lecturer clicks on create a new course.
Contains at least:
- Option to create chapters 
- Add media content to chapters
- Add dates to chapters / learning material, the learning material should not be accessible to students before that date
- Add a critical path that must be followed (first lecture 1, then 2, then quiz 1 must be passed to unlock next lecture)
- Not all learning material must be part of the critical path, there can for example be an extra quiz that is not necessary to unlock a lecture
Think about what else needs to be or could be on that page.

## Acceptance Criteria
- [ ] if something was missing in the initial description communicate with Loic
- [ ] page works without backend
- [ ] documentation is updated

## Sub-issues / Children
#11 
#12 
#25
